name       : citra
version    : 1990
release    : 8
source     :
    - git|https://github.com/citra-emu/citra-nightly : nightly-1990
license    : GPL-2.0-or-later
component  : games.emulator
summary    : An experimental open-source Nintendo 3DS emulator.
description: |
    Citra is an emulator for the Nintendo 3DS handheld. It is capable of running and debugging homebrew applications, as well as many commercial games.
builddeps  :
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(libavcodec)
    - pkgconfig(libssl)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libunwind)
    - pkgconfig(libusb-1.0)
    - pkgconfig(sdl2)
    - glslang
    - libboost-devel
    - robin-map
setup      : |
    %cmake_ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCITRA_USE_BUNDLED_QT=OFF \
        -DCITRA_USE_BUNDLED_FFMPEG=OFF \
        -DENABLE_QT_UPDATER=OFF \
        -DUSE_SYSTEM_BOOST=ON \
        -DUSE_SYSTEM_SDL2=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/citra.appdata.xml $installdir/usr/share/metainfo/citra.appdata.xml
