name       : citra
version    : 1821
release    : 4
source     :
    - git|https://github.com/citra-emu/citra-nightly : nightly-1821
license    : GPL-2.0-or-later
component  : games.emulator
summary    : An experimental open-source Nintendo 3DS emulator.
description: |
    Citra is an emulator for the Nintendo 3DS handheld. It is capable of running and debugging homebrew applications, as well as many commercial games.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(fdk-aac)
    - pkgconfig(libusb-1.0)
    - pkgconfig(sdl2)
    - robin-map
setup      : |
    %cmake_ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DDYNARMIC_NO_BUNDLED_ROBIN_MAP=TRUE
build      : |
    %ninja_build
install    : |
    %ninja_install
